version: "3.8"
services:
    web:
        container_name: rtl-tvmaze-scraper-app
        build: .
        image: sobdeijn/rtl-tvmaze-scraper
        ports:
            - "8080:80"
        environment:
            - "ConnectionStrings:DefaultConnection=Server=db;Database=TvMaze;User Id=sa;Password=Your_password123"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"
        container_name: rtl-tvmaze-scraper-db